name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygbag
      
      - name: Check compatibility
        run: |
          python3 check_compatibility.py
      
      - name: Build WebAssembly version
        run: |
          # Pygbag builds the game for web
          # --build: Create production build
          # --template noctx.tmpl: Use no-context template for better compatibility
          pygbag --build --template noctx.tmpl .
      
      - name: Enhance web build
        run: |
          echo "🎨 Adding loading bar and error console..."
          python3 enhance_web_build.py
      
      - name: Verify build output
        run: |
          echo "Build complete. Checking output..."
          ls -la build/web/
          echo "Build size:"
          du -sh build/web/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Display deployment URL
        run: |
          echo "🎉 Deployment successful!"
          echo "🌐 Game is now live at: ${{ steps.deployment.outputs.page_url }}"
